step_introspect: true

control_memory: 6144
compute_memory: 6144

undercloud_memory: 8192
undercloud_vcpu: 2

overcloud_nodes:
  - name: control_0
    flavor: control

  - name: compute_0
    flavor: compute

extra_args: "--debug --swift-storage-flavor oooq_ceph --block-storage-flavor oooq_ceph --neutron-network-type vxlan --neutron-tunnel-types vxlan -e /usr/share/openstack-tripleo-heat-templates/environments/network-isolation.yaml -e /usr/share/openstack-tripleo-heat-templates/environments/net-single-nic-with-vlans.yaml -e ~/network-environment.yaml --ntp-server pool.ntp.org"
tempest: false
pingtest: true
