---
- include: provision.yml

- name:  Setup undercloud and baremetal vms and networks in libvirt
  hosts: virthost
  gather_facts: yes
  roles:
    - libvirt/teardown
    - libvirt/setup

# Add the undercloud node to the generated
# inventory.
- name:  Inventory the undercloud
  hosts: localhost
  gather_facts: yes
  vars:
      inventory: undercloud
  roles:
    - tripleo-inventory

- name:  Install the undercloud
  hosts: undercloud
  gather_facts: no
  roles:
    - tripleo/undercloud

- name:  Post undercloud install steps
  hosts: undercloud
  gather_facts: no
  roles:
    - ansible-role-tripleo-undercloud-post

- name:  Deploy the overcloud
  hosts: undercloud
  gather_facts: no
  roles:
    - ansible-role-tripleo-overcloud

- name:  Inventory the overcloud
  hosts: undercloud
  gather_facts: yes
  vars:
      inventory: all
  roles:
    - tripleo-inventory

- name:  validate the overcloud
  hosts: undercloud
  gather_facts: no
  roles:
    - ansible-role-tripleo-overcloud-validate
